name: linux-builds

on:
  push:
  workflow_dispatch:

jobs:
  build_ubuntu_2204_cmake:
    runs-on: ubuntu-22.04

    env:
      QT_VERSION: 6.4.2
      QT_DIR: ${{ github.workspace }}/Qt

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history and tags

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libxkbcommon-x11-0 \
            libxkbcommon-dev \
            libx11-dev \
            libxcb1-dev \
            libxcb-render0-dev \
            libxcb-shape0-dev \
            libxcb-randr0-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          target: desktop
          host: linux
          arch: gcc_64
          modules: 'qtcharts qtshadertools'
          dir: ${{ env.QT_DIR }}
          setup-python: false

      - name: Configure with CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_PREFIX_PATH="${{ env.QT_DIR }}/Qt/${{ env.QT_VERSION }}/gcc_64" \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install \
            -DCMAKE_BUILD_TYPE=Release \
            -G Ninja

      - name: Build
        run: cmake --build build

      - name: Run CMake install (optional)
        run: cmake --install build

  build_ubuntu_2204:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Cache Qt
        id: cache-qt-6-4
        uses: actions/cache@v3
        with:
          path: ../Qt/6.4.2
          key: ${{ runner.os }}-QtCache-Qt6-4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.4.2'
          host: 'linux'
          target: 'desktop'
          install-deps: true
          modules: 'qtcharts qtshadertools'
          cached: ${{ steps.cache-qt-6-4.outputs.cache-hit }}
          setup-python: true
          tools: ''
          tools-only: false

      - name: Install dependencies (Charts + X11)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libxkbcommon-dev \
            libxcb1-dev \
            libxcb-render0-dev \
            libxcb-shape0-dev \
            libxcb-randr0-dev

      - name: Ubuntu and Qt version
        run: |
          cat /etc/issue
          echo number of processors: $(nproc)
          qmake -v

      - name: qmake
        run: qmake

      - name: make
        run: make -j$(nproc)